sudo: required

services:
  - docker

language: generic

before_script:
  - docker-compose build
script:
  - docker-compose run --rm tdb bash -c "bundle exec rake db:setup RAILS_ENV=test && bundle exec rake db:migrate RAILS_ENV=test && bundle exec rake spec"
