version: '3'
services:
  postgresql:
    image: postgres:10-alpine
    container_name: tdb-dev-postgresql
    env_file: .docker/variables.env
    ports:
      - 5433:5432

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: tdb-dev-app
    env_file: .docker/variables.env
    depends_on:
      - postgresql
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:80
      - 3035:3035