version: '3'
services:
  app:
    command: bash -c "yarn install --ignore-engines && rm -f tmp/pids/server.pid && rails s --port 80 --binding 0.0.0.0"
    environment:
      - RAILS_ENV=test
      - NODE_ENV=test